// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChannelsByServerID = `-- name: CountChannelsByServerID :one
SELECT COUNT(*) FROM channels
WHERE server_id = $1
`

func (q *Queries) CountChannelsByServerID(ctx context.Context, serverID string) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsByServerID, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
    id, name, type, server_id, position, max_participants
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, type, server_id, position, max_participants, created_at, updated_at
`

type CreateChannelParams struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	ServerID        string      `json:"server_id"`
	Position        int32       `json:"position"`
	MaxParticipants pgtype.Int4 `json:"max_participants"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ServerID,
		arg.Position,
		arg.MaxParticipants,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ServerID,
		&i.Position,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, type, server_id, position, max_participants, created_at, updated_at FROM channels
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChannelByID(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ServerID,
		&i.Position,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelsByServerID = `-- name: GetChannelsByServerID :many
SELECT id, name, type, server_id, position, max_participants, created_at, updated_at FROM channels
WHERE server_id = $1
ORDER BY position ASC
`

func (q *Queries) GetChannelsByServerID(ctx context.Context, serverID string) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannelsByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ServerID,
			&i.Position,
			&i.MaxParticipants,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = $2, type = $3, position = $4, max_participants = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, type, server_id, position, max_participants, created_at, updated_at
`

type UpdateChannelParams struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Position        int32       `json:"position"`
	MaxParticipants pgtype.Int4 `json:"max_participants"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Position,
		arg.MaxParticipants,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ServerID,
		&i.Position,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
