// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (
    id, code, server_id, single_use, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, code, server_id, created_at, expires_at, used, single_use, used_by_id, used_at
`

type CreateInviteParams struct {
	ID        string           `json:"id"`
	Code      string           `json:"code"`
	ServerID  string           `json:"server_id"`
	SingleUse pgtype.Bool      `json:"single_use"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.Code,
		arg.ServerID,
		arg.SingleUse,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ServerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Used,
		&i.SingleUse,
		&i.UsedByID,
		&i.UsedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, code, server_id, created_at, expires_at, used, single_use, used_by_id, used_at FROM invites
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ServerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Used,
		&i.SingleUse,
		&i.UsedByID,
		&i.UsedAt,
	)
	return i, err
}

const getInvitesByServerID = `-- name: GetInvitesByServerID :many
SELECT id, code, server_id, created_at, expires_at, used, single_use, used_by_id, used_at FROM invites
WHERE server_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInvitesByServerID(ctx context.Context, serverID string) ([]Invite, error) {
	rows, err := q.db.Query(ctx, getInvitesByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ServerID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Used,
			&i.SingleUse,
			&i.UsedByID,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvite = `-- name: UpdateInvite :one
UPDATE invites
SET used = $2, used_by_id = $3, used_at = CURRENT_TIMESTAMP
WHERE code = $1
RETURNING id, code, server_id, created_at, expires_at, used, single_use, used_by_id, used_at
`

type UpdateInviteParams struct {
	Code     string      `json:"code"`
	Used     pgtype.Bool `json:"used"`
	UsedByID pgtype.Text `json:"used_by_id"`
}

func (q *Queries) UpdateInvite(ctx context.Context, arg UpdateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, updateInvite, arg.Code, arg.Used, arg.UsedByID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ServerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Used,
		&i.SingleUse,
		&i.UsedByID,
		&i.UsedAt,
	)
	return i, err
}

