// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	Type            string           `json:"type"`
	ServerID        string           `json:"server_id"`
	Position        int32            `json:"position"`
	MaxParticipants pgtype.Int4      `json:"max_participants"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Invite struct {
	ID        string           `json:"id"`
	Code      string           `json:"code"`
	ServerID  string           `json:"server_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Used      pgtype.Bool      `json:"used"`
	SingleUse pgtype.Bool      `json:"single_use"`
	UsedByID  pgtype.Text      `json:"used_by_id"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
}

type Message struct {
	ID        string           `json:"id"`
	Content   string           `json:"content"`
	UserID    string           `json:"user_id"`
	ChannelID string           `json:"channel_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Notification struct {
	ID        string           `json:"id"`
	Type      string           `json:"type"`
	Title     string           `json:"title"`
	Message   string           `json:"message"`
	UserID    string           `json:"user_id"`
	Read      pgtype.Bool      `json:"read"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Reaction struct {
	ID        string           `json:"id"`
	Emoji     string           `json:"emoji"`
	MessageID string           `json:"message_id"`
	UserID    string           `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Server struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Icon        pgtype.Text      `json:"icon"`
	OwnerID     string           `json:"owner_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ServerMember struct {
	ID       string           `json:"id"`
	ServerID string           `json:"server_id"`
	UserID   string           `json:"user_id"`
	Role     pgtype.Text      `json:"role"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}

type User struct {
	ID            string           `json:"id"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	Password      string           `json:"password"`
	Discriminator string           `json:"discriminator"`
	Avatar        pgtype.Text      `json:"avatar"`
	Status        pgtype.Text      `json:"status"`
	Bio           pgtype.Text      `json:"bio"`
	Location      pgtype.Text      `json:"location"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type VoiceState struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	ChannelID  pgtype.Text      `json:"channel_id"`
	IsMuted    pgtype.Bool      `json:"is_muted"`
	IsDeafened pgtype.Bool      `json:"is_deafened"`
	IsSpeaking pgtype.Bool      `json:"is_speaking"`
	JoinedAt   pgtype.Timestamp `json:"joined_at"`
}
