// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (
    id, name, description, icon, owner_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, description, icon, owner_id, created_at, updated_at
`

type CreateServerParams struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	OwnerID     string      `json:"owner_id"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.OwnerID,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServerMember = `-- name: CreateServerMember :one
INSERT INTO server_members (
    id, server_id, user_id, role
) VALUES (
    $1, $2, $3, $4
) RETURNING id, server_id, user_id, role, joined_at
`

type CreateServerMemberParams struct {
	ID       string      `json:"id"`
	ServerID string      `json:"server_id"`
	UserID   string      `json:"user_id"`
	Role     pgtype.Text `json:"role"`
}

func (q *Queries) CreateServerMember(ctx context.Context, arg CreateServerMemberParams) (ServerMember, error) {
	row := q.db.QueryRow(ctx, createServerMember,
		arg.ID,
		arg.ServerID,
		arg.UserID,
		arg.Role,
	)
	var i ServerMember
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers
WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const deleteServerMember = `-- name: DeleteServerMember :exec
DELETE FROM server_members
WHERE server_id = $1 AND user_id = $2
`

type DeleteServerMemberParams struct {
	ServerID string `json:"server_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) DeleteServerMember(ctx context.Context, arg DeleteServerMemberParams) error {
	_, err := q.db.Exec(ctx, deleteServerMember, arg.ServerID, arg.UserID)
	return err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, description, icon, owner_id, created_at, updated_at FROM servers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServerByID(ctx context.Context, id string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerMember = `-- name: GetServerMember :one
SELECT id, server_id, user_id, role, joined_at FROM server_members
WHERE server_id = $1 AND user_id = $2 LIMIT 1
`

type GetServerMemberParams struct {
	ServerID string `json:"server_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) GetServerMember(ctx context.Context, arg GetServerMemberParams) (ServerMember, error) {
	row := q.db.QueryRow(ctx, getServerMember, arg.ServerID, arg.UserID)
	var i ServerMember
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getServerMembers = `-- name: GetServerMembers :many
SELECT id, server_id, user_id, role, joined_at FROM server_members
WHERE server_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) GetServerMembers(ctx context.Context, serverID string) ([]ServerMember, error) {
	rows, err := q.db.Query(ctx, getServerMembers, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerMember{}
	for rows.Next() {
		var i ServerMember
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerMembersWithUsers = `-- name: GetServerMembersWithUsers :many
SELECT sm.id, sm.server_id, sm.user_id, sm.role, sm.joined_at, u.id as user_id, u.username, u.email, u.discriminator, u.avatar, u.status, u.bio, u.location
FROM server_members sm
INNER JOIN users u ON sm.user_id = u.id
WHERE sm.server_id = $1
ORDER BY sm.joined_at ASC
`

type GetServerMembersWithUsersRow struct {
	ID            string           `json:"id"`
	ServerID      string           `json:"server_id"`
	UserID        string           `json:"user_id"`
	Role          pgtype.Text      `json:"role"`
	JoinedAt      pgtype.Timestamp `json:"joined_at"`
	UserID_2      string           `json:"user_id_2"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	Discriminator string           `json:"discriminator"`
	Avatar        pgtype.Text      `json:"avatar"`
	Status        pgtype.Text      `json:"status"`
	Bio           pgtype.Text      `json:"bio"`
	Location      pgtype.Text      `json:"location"`
}

func (q *Queries) GetServerMembersWithUsers(ctx context.Context, serverID string) ([]GetServerMembersWithUsersRow, error) {
	rows, err := q.db.Query(ctx, getServerMembersWithUsers, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetServerMembersWithUsersRow{}
	for rows.Next() {
		var i GetServerMembersWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.UserID_2,
			&i.Username,
			&i.Email,
			&i.Discriminator,
			&i.Avatar,
			&i.Status,
			&i.Bio,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserServers = `-- name: GetUserServers :many
SELECT s.id, s.name, s.description, s.icon, s.owner_id, s.created_at, s.updated_at FROM servers s
INNER JOIN server_members sm ON s.id = sm.server_id
WHERE sm.user_id = $1
ORDER BY s.created_at DESC
`

func (q *Queries) GetUserServers(ctx context.Context, userID string) ([]Server, error) {
	rows, err := q.db.Query(ctx, getUserServers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServer = `-- name: UpdateServer :one
UPDATE servers
SET name = $2, description = $3, icon = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, icon, owner_id, created_at, updated_at
`

type UpdateServerParams struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServer,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
