// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, username, email, password, discriminator, avatar, status, bio, location
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at
`

type CreateUserParams struct {
	ID            string      `json:"id"`
	Username      string      `json:"username"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Discriminator string      `json:"discriminator"`
	Avatar        pgtype.Text `json:"avatar"`
	Status        pgtype.Text `json:"status"`
	Bio           pgtype.Text `json:"bio"`
	Location      pgtype.Text `json:"location"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Discriminator,
		arg.Avatar,
		arg.Status,
		arg.Bio,
		arg.Location,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByDiscriminator = `-- name: GetUserByDiscriminator :one
SELECT id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at FROM users
WHERE discriminator = $1 LIMIT 1
`

func (q *Queries) GetUserByDiscriminator(ctx context.Context, discriminator string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscriminator, discriminator)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at FROM users
WHERE email = $1 OR username = $2
LIMIT 1
`

type GetUserByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, arg GetUserByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, email, discriminator, avatar, status, bio, location, created_at, updated_at FROM users
ORDER BY created_at DESC
`

type GetUsersRow struct {
	ID            string           `json:"id"`
	Username      string           `json:"username"`
	Email         string           `json:"email"`
	Discriminator string           `json:"discriminator"`
	Avatar        pgtype.Text      `json:"avatar"`
	Status        pgtype.Text      `json:"status"`
	Bio           pgtype.Text      `json:"bio"`
	Location      pgtype.Text      `json:"location"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Discriminator,
			&i.Avatar,
			&i.Status,
			&i.Bio,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, email = $3, avatar = $4, status = $5, bio = $6, location = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at
`

type UpdateUserParams struct {
	ID       string      `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Avatar   pgtype.Text `json:"avatar"`
	Status   pgtype.Text `json:"status"`
	Bio      pgtype.Text `json:"bio"`
	Location pgtype.Text `json:"location"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Avatar,
		arg.Status,
		arg.Bio,
		arg.Location,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, email, password, discriminator, avatar, status, bio, location, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     string      `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Discriminator,
		&i.Avatar,
		&i.Status,
		&i.Bio,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
